apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: webhost
      image: syamapatra/syama:v1
      ports:
        - name: web
          containerPort: 80
          protocol: TCP